'use client';
import { useEffect, useState } from 'react';

type Invoice = { id:string; number:string; total:string; currency:string; status:string; customer?:{name:string}|null; business:{name:string} };
export default function PayPage({ params }: { params: Promise<{id:string}> }) {
 const [invoice,setInvoice]=useState<Invoice|null>(null),[phone,setPhone]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 useEffect(()=>{params.then(async p=>{const r=await fetch(`/api/public/invoice/${p.id}`);const d=await r.json();if(r.ok)setInvoice(d.invoice);else setMessage(d.error||'Invoice not found.');setLoading(false)}).catch(()=>{setMessage('Unable to load invoice.');setLoading(false)})},[params]);
 async function pay(e:React.FormEvent){e.preventDefault();if(!invoice)return;setBusy(true);setMessage('');const r=await fetch('/api/public/paytota/invoice',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({invoiceId:invoice.id,phone})});const d=await r.json();setMessage(r.ok?d.message:(d.error||'Unable to start payment.'));setBusy(false)}
 if(loading)return <main className="auth"><section className="card"><p>Loading invoice…</p></section></main>;
 return <main className="auth"><section className="card"><div className="eyebrow">MerchantPay payment</div>{invoice?<><h1>{invoice.business.name}</h1><p className="muted">Invoice {invoice.number}{invoice.customer?.name?` · ${invoice.customer.name}`:''}</p><div className="metrics"><div className="metric"><span className="muted">Amount</span><strong>{invoice.currency} {Number(invoice.total).toLocaleString()}</strong></div><div className="metric"><span className="muted">Status</span><strong>{invoice.status}</strong></div></div>{invoice.status!=='PAID'&&invoice.status!=='CANCELLED'?<form className="form" onSubmit={pay}><label>Mobile money number<input value={phone} onChange={e=>setPhone(e.target.value)} type="tel" placeholder="+256 7XX XXX XXX" required/><small className="muted">You will receive a mobile money prompt to approve the payment.</small></label>{message&&<div className={message.toLowerCase().includes('sent')?'success':'error'}>{message}</div>}<button className="btn primary" disabled={busy}>{busy?'Sending payment request…':'Pay with Mobile Money'}</button></form>:<p className="success">This invoice is already {invoice.status.toLowerCase()}.</p>}</>:<p className="error">{message}</p>}</section></main>;
}
