"use client";
import {useEffect,useState} from "react";
type S={testMode:boolean,basicLive:number,plusLive:number,proLive:number,platinumLive:number,basicTest:number,plusTest:number,proTest:number,platinumTest:number,liveExpirationMinutes:number,testExpirationMinutes:number};
const initial:S={testMode:false,basicLive:0,plusLive:25000,proLive:58000,platinumLive:102000,basicTest:0,plusTest:100,proTest:200,platinumTest:300,liveExpirationMinutes:43200,testExpirationMinutes:3};
const fields:[keyof S,string][]=[["basicLive","Basic live"],["plusLive","Plus live"],["proLive","Pro live"],["platinumLive","Platinum live"],["basicTest","Basic test"],["plusTest","Plus test"],["proTest","Pro test"],["platinumTest","Platinum test"]];
const duration=(m:number)=>m>=1440?`${m} minutes (${(m/1440).toFixed(m%1440?2:0)} days)`:m>=60?`${m} minutes (${(m/60).toFixed(m%60?2:0)} hours)`:`${m} minutes`;
export default function PlatformSettings(){
 const[s,setS]=useState<S>(initial),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[msg,setMsg]=useState("");
 useEffect(()=>{fetch('/api/admin/platform-settings',{cache:'no-store'}).then(async r=>{if(!r.ok)throw new Error();return r.json()}).then(d=>setS({...initial,...d})).catch(()=>setMsg('Unable to load platform settings.')).finally(()=>setLoading(false))},[]);
 const change=(k:keyof S,v:any)=>setS(x=>({...x,[k]:v}));
 async function save(){setSaving(true);setMsg("");try{const payload:any={...s};delete payload.id;delete payload.updatedAt;const r=await fetch('/api/admin/platform-settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to save settings');setS(x=>({...x,...d}));setMsg(s.testMode?'TEST MODE ACTIVE — prices and test expiration saved.':'LIVE MODE ACTIVE — prices and live expiration saved.')}catch(e:any){setMsg(e.message||'Unable to save settings.')}finally{setSaving(false)}}
 async function toggle(){const next=!s.testMode;if(next&&!confirm('Enable TEST MODE? MerchantPay will use the test prices and TEST expiration period. The mode change is automatically recorded.'))return;if(!next&&!confirm('Switch to LIVE MODE? Live prices and the LIVE expiration period will be used.'))return;setSaving(true);setMsg("");try{const r=await fetch('/api/admin/platform-settings',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({testMode:next})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to change mode');setS(x=>({...x,testMode:d.testMode}));setMsg(next?'TEST MODE ACTIVE — automatic audit record created.':'LIVE MODE ACTIVE — automatic audit record created.')}catch(e:any){setMsg(e.message||'Unable to change mode.')}finally{setSaving(false)}}
 return <section className="panel platform-settings"><div className="section-heading"><div><h2>Subscription pricing, expiration & test mode</h2><p className="muted">Only the Super Admin can change these development settings. Test and Live values are stored separately.</p></div><span className={`mode-badge ${s.testMode?'test':'live'}`}>{s.testMode?'🧪 TEST MODE ACTIVE':'● LIVE MODE ACTIVE'}</span></div>{loading?<p className="muted">Loading platform settings…</p>:<><div className="mode-row"><div><strong>{s.testMode?'Test Mode':'Live Mode'}</strong><p className="muted">{s.testMode?'Subscription flows read Test prices and the Test expiration period.':'Subscription flows read Live prices and the Live expiration period.'}</p></div><button type="button" className={`btn ${s.testMode?'danger-btn':'primary'}`} disabled={saving} onClick={toggle}>{s.testMode?'Switch to Live Mode':'Enable Test Mode'}</button></div><div className="price-grid"><div><h3>Live configuration</h3>{fields.filter(([k])=>String(k).endsWith('Live')).map(([k,label])=><label key={String(k)}>{label.replace(' live','')}<input type="number" min="0" value={s[k] as number} onChange={e=>change(k,Math.max(0,Number(e.target.value)||0))}/></label>)}<label>Expiration period (minutes)<input type="number" min="1" value={s.liveExpirationMinutes} onChange={e=>change('liveExpirationMinutes',Math.max(1,Math.floor(Number(e.target.value)||1)))}/></label><small className="muted">{duration(s.liveExpirationMinutes)}</small></div><div><h3>Test configuration</h3>{fields.filter(([k])=>String(k).endsWith('Test')).map(([k,label])=><label key={String(k)}>{label.replace(' test','')}<input type="number" min="0" value={s[k] as number} onChange={e=>change(k,Math.max(0,Number(e.target.value)||0))}/></label>)}<label>Expiration period (minutes)<input type="number" min="1" value={s.testExpirationMinutes} onChange={e=>change('testExpirationMinutes',Math.max(1,Math.floor(Number(e.target.value)||1)))}/></label><small className="muted">{duration(s.testExpirationMinutes)}</small></div></div><div className="mode-note"><strong>How expiration works:</strong> when a subscription period is created/renewed, MerchantPay uses the currently active mode's expiration period and stores the exact renewal/change time and exact expiry timestamp. Existing active subscriptions keep their current expiry unless the subscription flow explicitly creates a new period.</div><button type="button" className="btn primary" disabled={saving} onClick={save}>{saving?'Saving…':'Save prices & expiration periods'}</button>{msg&&<p className={msg.includes('Unable')?'error':'success'}>{msg}</p>}</>}</section>
}
