import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import Link from "next/link";
import { db } from "@/lib/db";

export default async function BusinessProfile(){
 const c=await cookies(); const uid=c.get("merchantpay_session")?.value?.split(".")[0]; if(!uid)redirect("/login");
 const m=await db.businessMember.findFirst({where:{userId:uid},include:{business:{include:{subscription:true}},user:true}}); if(!m)redirect("/onboarding"); if(m.business.suspended)redirect("/dashboard/suspended");
 const sub=m.business.subscription; const expires=sub?.expiresAt; const days=expires?Math.max(0,Math.ceil((expires.getTime()-Date.now())/86400000)):null;
 return <main className="dash"><aside className="side"><Link className="brand-inline profile-brand" href="/dashboard/profile">{m.business.logoData?<img className="dashboard-logo" src={m.business.logoData} alt="Business logo"/>:<span className="brand-placeholder">{m.business.name.slice(0,1).toUpperCase()}</span>}<strong>{m.business.name}</strong></Link><nav className="nav"><Link href="/dashboard">Dashboard</Link><Link href="/dashboard/invoices">Invoices</Link><Link href="/dashboard/payments">Payments</Link><Link href="/dashboard/customers">Customers</Link><Link href="/dashboard/items">Products</Link><Link href="/dashboard/reports">Reports</Link><Link href="/dashboard/settings">Settings</Link></nav></aside><section className="main"><div className="top"><div><p className="muted">Business profile</p><h1>{m.business.name}</h1><p className="muted">Your registered MerchantPay business information.</p></div><Link className="btn" href="/dashboard/settings">Edit settings</Link></div><section className="panel profile-card">{m.business.logoData?<img className="profile-logo" src={m.business.logoData} alt={`${m.business.name} logo`}/>:<div className="profile-logo placeholder-large">{m.business.name.slice(0,1).toUpperCase()}</div>}<div className="profile-details"><div><span className="muted">Business name</span><strong>{m.business.name}</strong></div><div><span className="muted">Business phone</span><strong>{m.business.phone||"Not provided"}</strong></div><div><span className="muted">Customer-payment payout number</span><strong>{m.business.mobileMoneyPhone||"Not configured"}</strong></div><div><span className="muted">Currency</span><strong>{m.business.currency}</strong></div><div><span className="muted">Account email</span><strong>{m.user.email}</strong></div></div></section><section className="panel"><h2>Subscription</h2><div className="subscription-current"><div><span className="muted">Current plan</span><strong>{sub?.plan||"BASIC"}</strong></div><div><span className="muted">Status</span><strong>{sub?.status||"ACTIVE"}</strong></div><div><span className="muted">Time remaining</span><strong>{days===null?"Free plan — no expiry":days===0?"Expires today":`${days} day${days===1?"":"s"}`}</strong></div></div>{expires&&<p className="muted">Subscription expiry: {expires.toLocaleDateString()}</p>}</section></section></main>
}
