"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
type Plan={key:string;name:string;price:number;limit:number|null;description:string};
type Data={preferences?:{theme:string;appearance:string};business:{name:string;phone:string|null;mobileMoneyPhone:string|null;mobileMoneyNetwork:string|null;currency:string;logoData:string|null};subscription:{plan:string;status:string;effectiveStatus:string;maxInvoices:number|null;expiresAt:string|null;lastPlanChangedAt?:string|null};plans:Plan[]};
export default function SettingsPage(){
 const [data,setData]=useState<Data|null>(null),[pwCurrent,setPwCurrent]=useState(""),[pwNew,setPwNew]=useState(""),[pwMsg,setPwMsg]=useState(""),[showInvoices,setShowInvoices]=useState(false),[invoiceRows,setInvoiceRows]=useState<any[]>([]),[announcements,setAnnouncements]=useState<any[]>([]),[theme,setTheme]=useState("indigo"),[appearance,setAppearance]=useState("light"),[feedbackSubject,setFeedbackSubject]=useState(""),[feedbackMessage,setFeedbackMessage]=useState(""),[feedbackStatus,setFeedbackStatus]=useState(""),[name,setName]=useState(""),[phone,setPhone]=useState(""),[mobileMoneyPhone,setMobileMoneyPhone]=useState(""),[mobileMoneyNetwork,setMobileMoneyNetwork]=useState("MTN"),[currency,setCurrency]=useState("UGX"),[logo,setLogo]=useState<string|null>(null),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{fetch("/api/announcements").then(r=>r.ok?r.json():[]).then(setAnnouncements).catch(()=>{});fetch("/api/settings").then(r=>r.json()).then(d=>{if(d.business){setData(d);setTheme(d.preferences?.theme||"indigo");setAppearance(d.preferences?.appearance||"light");document.documentElement.dataset.theme=d.preferences?.theme||"indigo";document.documentElement.dataset.appearance=d.preferences?.appearance||"light";setName(d.business.name);setPhone(d.business.phone||"");setMobileMoneyPhone(d.business.mobileMoneyPhone||"");setMobileMoneyNetwork(d.business.mobileMoneyNetwork||"MTN");setCurrency(d.business.currency||"UGX");setLogo(d.business.logoData||null);}})},[]);
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("");try{const r=await fetch("/api/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({businessName:name,phone,mobileMoneyPhone,mobileMoneyNetwork,currency,logoData:logo})});const d=await r.json();setMessage(r.ok?"Settings saved successfully.":(d.error||"Unable to save settings."));if(r.ok)setData(prev=>prev?{...prev,business:{...prev.business,name,phone,currency,logoData:logo}}:prev)}finally{setSaving(false)}}
 function pickLogo(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(!["image/png","image/jpeg","image/webp"].includes(f.type)){setMessage("Please choose a PNG, JPG or WebP image.");return}if(f.size>800*1024){setMessage("Please choose an image smaller than 800 KB.");return}const reader=new FileReader();reader.onload=()=>setLogo(String(reader.result));reader.readAsDataURL(f)}
 if(!data)return <main className="dash"><section className="main"><p>Loading settings…</p></section></main>;
 const current=data.plans.find(p=>p.key===data.subscription.plan)||data.plans[0];
 const subscriptionExpired=data.subscription.effectiveStatus==="EXPIRED";
 const changePlan=async(plan:string,renew=false)=>{const r=await fetch('/api/subscription/plan',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan,action:renew?'renew':undefined})});const d=await r.json();if(r.status===402){const p=await fetch('/api/paytota/subscription',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan})});const pd=await p.json();if(p.ok){alert(pd.message||'Payment request sent. Approve the mobile money prompt.');return}alert(pd.error||'Unable to start subscription payment.');return}if(r.ok)location.reload();else alert(d.error||'Unable to change subscription.');};
 const changeTheme=async(value:string)=>{setTheme(value);document.documentElement.dataset.theme=value;await fetch("/api/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({theme:value})})};
 const changeAppearance=async(value:string)=>{setAppearance(value);document.documentElement.dataset.appearance=value;await fetch("/api/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({appearance:value})})};
 return <main className="dash"><aside className="side"><strong>MerchantPay</strong><nav className="nav"><Link href="/dashboard">Dashboard</Link><Link href="/dashboard/invoices">Invoices</Link><Link href="/dashboard/payments">Payments</Link><Link href="/dashboard/customers">Customers</Link><Link href="/dashboard/items">Products &amp; Services</Link><Link className="active" href="/dashboard/settings">Settings</Link></nav></aside><section className="main">
 <div className="top"><div><p className="muted">Business settings</p><h1>Settings</h1><p className="muted">Manage your business identity and subscription.</p></div><form action="/api/logout" method="post"><button className="btn">Sign out</button></form></div>
 <section className="panel"><h2>Business profile</h2><p className="muted">Customer invoice payments will be paid out to this saved mobile money number: <strong>{data.business.mobileMoneyPhone||"Not set"}</strong></p><p className="muted">Your logo appears across your MerchantPay workspace.</p><form className="form" onSubmit={save}><label>Business name<input value={name} onChange={e=>setName(e.target.value)} required/></label><label>Phone<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Business phone"/></label><label>Mobile money payout number<input value={mobileMoneyPhone} onChange={e=>setMobileMoneyPhone(e.target.value)} placeholder="+256 7XX XXX XXX" required/><small className="muted">This mobile phone number will receive the customer invoice payments, ensure it's the right one.</small></label><label>Mobile money network<select value={mobileMoneyNetwork} onChange={e=>setMobileMoneyNetwork(e.target.value)}><option value="MTN">MTN Mobile Money</option><option value="AIRTEL">Airtel Money</option></select></label><label>Currency<input value={currency} onChange={e=>setCurrency(e.target.value)} maxLength={3}/></label><label>Business logo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={pickLogo}/></label>{logo?<div className="logo-preview"><img src={logo} alt="Business logo preview"/><button type="button" className="btn danger" onClick={()=>setLogo(null)}>Remove logo</button></div>:<div className="empty">No business logo uploaded.</div>}<button className="btn primary" disabled={saving}>{saving?"Saving…":"Save settings"}</button>{message&&<p className={message.includes("success")?"success":"error"}>{message}</p>}</form></section>
 <section className="panel"><div className="section-heading"><div><h2>Subscription</h2><p className="muted">Your current plan controls how many invoices your business can create.</p></div><span className="status-pill">{data.subscription.effectiveStatus}</span></div><div className="subscription-current"><div><span className="muted">Current plan</span><strong>{current.name}</strong></div><div><span className="muted">Invoice allowance</span><strong>{current.limit===null?"Unlimited":current.limit}</strong></div><div><span className="muted">Expires</span><strong>{data.subscription.expiresAt?new Date(data.subscription.expiresAt).toLocaleString():"No expiry set yet"}</strong></div><div><span className="muted">Last plan change</span><strong>{data.subscription.lastPlanChangedAt?new Date(data.subscription.lastPlanChangedAt).toLocaleString():"No plan change recorded"}</strong></div><div><span className="muted">Invoices used</span><button className="link-button" onClick={async()=>{const r=await fetch("/api/invoices");const d=await r.json();setInvoiceRows(Array.isArray(d)?d:(d.invoices||[]));setShowInvoices(true)}}>View invoices</button></div></div><div className="plan-grid">{data.plans.map(p=><article className={p.key===current.key?"plan-card selected":"plan-card"} key={p.key}><div><span className="eyebrow">{p.name}</span><h3>{p.price===0?"Free":`UGX ${p.price.toLocaleString()}`}</h3><p className="muted">{p.description}</p></div><strong>{p.limit===null?"Unlimited invoices":`${p.limit} invoices`}</strong>{p.key===current.key?(subscriptionExpired?<button className="btn primary" onClick={()=>changePlan(p.key,true)}>Renew this plan</button>:<span className="status-pill">Current plan</span>):<button className="btn" onClick={()=>changePlan(p.key)}>Switch to {p.name}</button>}</article>)}</div></section>
 <section className="panel"><h2>Appearance & account theme</h2><p className="muted">Choose light or dark mode, then select your accent color.</p><div className="theme-controls"><label>Appearance<select value={appearance} onChange={e=>changeAppearance(e.target.value)}><option value="light">Light (default)</option><option value="dark">Dark</option></select></label><label>Accent color<select value={theme} onChange={e=>changeTheme(e.target.value)}><option value="indigo">Indigo</option><option value="emerald">Emerald</option><option value="violet">Violet</option><option value="rose">Rose</option><option value="amber">Amber</option></select></label></div></section>
 <section className="panel"><h2>Announcements</h2>{announcements.length?<div className="modal-list">{announcements.map((a:any)=><article key={a.id} className="message-card"><strong>{a.subject}</strong><p>{a.message}</p><small className="muted">{new Date(a.createdAt).toLocaleString()}</small></article>)}</div>:<p className="muted">No announcements yet.</p>}</section><section className="panel"><h2>Change password</h2><form className="form" onSubmit={async e=>{e.preventDefault();const r=await fetch('/api/account/password',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({currentPassword:pwCurrent,newPassword:pwNew})});const d=await r.json();setPwMsg(r.ok?'Password changed successfully.':d.error)}}><label>Current password<input type="password" value={pwCurrent} onChange={e=>setPwCurrent(e.target.value)} required/></label><label>New password<input type="password" minLength={8} value={pwNew} onChange={e=>setPwNew(e.target.value)} required/></label><button className="btn primary">Change password</button>{pwMsg&&<p>{pwMsg}</p>}</form></section><section className="panel"><h2>Send feedback to MerchantPay</h2><p className="muted">Share a bug, recommendation or idea with the administrator.</p><form className="form" onSubmit={async e=>{e.preventDefault();setFeedbackStatus("Sending…");const r=await fetch("/api/feedback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subject:feedbackSubject,message:feedbackMessage})});const d=await r.json();if(r.ok){setFeedbackSubject("");setFeedbackMessage("");setFeedbackStatus("Feedback sent successfully.")}else setFeedbackStatus(d.error||"Unable to send feedback.")}}><label>Subject<input value={feedbackSubject} onChange={e=>setFeedbackSubject(e.target.value)} required maxLength={120}/></label><label>Message<textarea value={feedbackMessage} onChange={e=>setFeedbackMessage(e.target.value)} required rows={5} maxLength={5000}/></label><button className="btn primary">Send feedback</button>{feedbackStatus&&<p className={feedbackStatus.includes("success")?"success":"error"}>{feedbackStatus}</p>}</form></section>
 {showInvoices&&<div className="modal-backdrop"><section className="modal-card"><button className="modal-close" onClick={()=>setShowInvoices(false)}>×</button><h2>Invoice allowance</h2><p><b>Created:</b> {invoiceRows.length}</p><p><b>Remaining:</b> {current.limit===null?'Unlimited':Math.max(0,current.limit-invoiceRows.length)}</p><div className="modal-list">{invoiceRows.map((x:any)=><div className="message-card" key={x.id}><strong>{x.number||x.id}</strong><small>{x.status}</small></div>)}</div></section></div>} </section></main>;
}
