"use client";
import { useEffect, useState } from 'react';
type Balance = { balance:number; fee_sell:number; reserved:number; gross_balance:number; payout_balance:number; payout_fee_sell:number; pending_payouts:number; payout_overdraft:number; pending_outgoing:number; available_balance:number; payout_gross_balance:number; available_payout_balance:number };
export default function PaytotaBalanceClient(){
 const [data,setData]=useState<Balance|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);try{const r=await fetch('/api/admin/paytota/balance',{cache:'no-store'});const d=await r.json();if(r.ok)setData(d.currencies?.UGX||null);else setError(d.error||'Unable to load Paytota balance.')}catch{setError('Unable to load Paytota balance.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 return <section className="panel"><div className="section-heading"><div><h2>Paytota account balance</h2><p className="muted">Live UGX balance and payout availability from Paytota.</p></div><button className="btn" onClick={load} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button></div>{error?<p className="error">{error}</p>:data?<div className="metrics"><div className="metric"><span>Balance</span><strong>UGX {data.balance.toLocaleString()}</strong></div><div className="metric"><span>Available balance</span><strong>UGX {data.available_balance.toLocaleString()}</strong></div><div className="metric"><span>Gross balance</span><strong>UGX {data.gross_balance.toLocaleString()}</strong></div><div className="metric"><span>Available payout balance</span><strong>UGX {data.available_payout_balance.toLocaleString()}</strong></div><div className="metric"><span>Payout balance</span><strong>UGX {data.payout_balance.toLocaleString()}</strong></div><div className="metric"><span>Reserved</span><strong>UGX {data.reserved.toLocaleString()}</strong></div><div className="metric"><span>Pending payouts</span><strong>UGX {data.pending_payouts.toLocaleString()}</strong></div><div className="metric"><span>Pending outgoing</span><strong>UGX {data.pending_outgoing.toLocaleString()}</strong></div><div className="metric"><span>Transaction fees</span><strong>UGX {data.fee_sell.toLocaleString()}</strong></div><div className="metric"><span>Payout fees</span><strong>UGX {data.payout_fee_sell.toLocaleString()}</strong></div><div className="metric"><span>Payout gross balance</span><strong>UGX {data.payout_gross_balance.toLocaleString()}</strong></div><div className="metric"><span>Payout overdraft</span><strong>UGX {data.payout_overdraft.toLocaleString()}</strong></div></div>:!loading?<p className="muted">No UGX balance was returned.</p>:<p className="muted">Loading balance…</p>}</section>
}
