'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';

type Payment={id:string;amount:string;currency:string;provider:string;providerReference:string|null;createdAt:string;invoice:{number:string;customer:{name:string}|null}};
export default function SuspendedPage(){
 const [business,setBusiness]=useState<any>(null),[payments,setPayments]=useState<Payment[]>([]),[subject,setSubject]=useState(''),[message,setMessage]=useState(''),[feedback,setFeedback]=useState(''),[loading,setLoading]=useState(true);
 useEffect(()=>{Promise.all([fetch('/api/preferences').then(r=>r.json()),fetch('/api/payments').then(r=>r.ok?r.json():{payments:[]})]).then(([p,d])=>{setBusiness(p.business);setPayments(d.payments||[])}).finally(()=>setLoading(false))},[]);
 async function send(e:React.FormEvent){e.preventDefault();setFeedback('Sending…');const r=await fetch('/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({subject,message})});const d=await r.json();if(r.ok){setSubject('');setMessage('');setFeedback('Message sent to the administrator.')}else setFeedback(d.error||'Unable to send message.')}
 if(loading)return <main className="auth"><section className="card"><p>Loading account status…</p></section></main>;
 return <main className="dash"><aside className="side"><strong>MerchantPay</strong><nav className="nav"><Link className="active" href="/dashboard/suspended">Account status</Link><Link href="/dashboard/payments">Payment history</Link></nav></aside><section className="main"><div className="top"><div><p className="muted">{business?.name||'Merchant account'}</p><h1>Account suspended</h1></div><form action="/api/logout" method="post"><button className="btn">Sign out</button></form></div>
 <section className="panel"><div className="error" style={{fontSize:'1rem'}}><strong>Your MerchantPay account has been suspended.</strong><p>{business?.suspensionReason||'Please contact the administrator for assistance.'}</p><p>While your account is suspended, you can only view your payment history and send a message to the administrator.</p></div></section>
 <section className="panel"><h2>Payment history</h2><p className="muted">Your completed payment records remain available while the account is suspended.</p>{payments.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Date</th><th>Invoice</th><th>Customer</th><th>Method</th><th>Reference</th><th className="number">Amount</th></tr></thead><tbody>{payments.map(p=><tr key={p.id}><td>{new Date(p.createdAt).toLocaleString()}</td><td>{p.invoice.number}</td><td>{p.invoice.customer?.name||'No customer'}</td><td>{p.provider.replaceAll('_',' ')}</td><td>{p.providerReference||'—'}</td><td className="number"><strong>{p.currency} {Number(p.amount).toLocaleString()}</strong></td></tr>)}</tbody></table></div>:<div className="empty">No completed payments yet.</div>}</section>
 <section className="panel"><h2>Contact administrator</h2><p className="muted">Use this form to ask why the account was suspended or request assistance.</p><form className="form" onSubmit={send}><label>Subject<input value={subject} onChange={e=>setSubject(e.target.value)} required maxLength={120}/></label><label>Message<textarea value={message} onChange={e=>setMessage(e.target.value)} required maxLength={5000} rows={6}/></label>{feedback&&<p className={feedback.includes('sent')?'success':'error'}>{feedback}</p>}<button className="btn primary">Send message to administrator</button></form></section>
 </section></main>;
}
